### ISSUE TITLE
close failed in file object destructor

### ISSUE THREAD

**Issue by isomorphisms** [jeroenjanssens/data-science-at-the-command-line#35]
Running your example `curl -s 'http://en.wikipedia.org/wiki/List_of_countries_and_territories_by_border/area_ratio' | scrape -b -e 'table.wikitable > tr:not(:first-child)' | head` I get:

```
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by jeroenjanssens** [comment]
Thanks. I guess I never saw that error before because I first save the all the output of `scrape` to a file, and then invoke `head` on that file (also because that means that you only have to run `curl` once, which is relatively time consuming in general).

Because the error is written to standard error, it wouldn't affect further processing in case you wanted to pipe the output of `head` to yet another command-line tool.

I'll have a look at the Python code. In the meantime, if you don't want to see the error, you can suppress it by appending `2>/dev/null` to the pipeline.

**Comment by jeroenjanssens** [comment]
I'm closing this. Please submit a PR if you want to have this fixed.
