### ISSUE TITLE
Ch2 Paste & Bc Example Not Working

### ISSUE THREAD

**Issue by lissahyacinth** [jeroenjanssens/data-science-at-the-command-line#87]
Example provided will cause an error with paste using Bash & Zsh on MacOS. Believe this will cause an issue on all variants, but haven't checked on Linux/Docker as of yet.

```
$ fac() { (echo 1; seq $1) | paste -s -d\* | bc; }
$ fac 5
> usage: paste [-s] [-d delimiters] file ...
```

Suggestion is to add in a ```-``` character, which will cause it to run correctly, making me think this is just an unchecked typo.

```
$ fac() { (echo 1; seq $1) | paste -s -d\* - | bc; }
$ fac 5
> 120
```

**Comment by jeroenjanssens** [comment]
This error happens because macOS has the BSD version of `paste` (and many other tools) installed by default. The book assumes the GNU versions of these tools, which are contained in the Docker image and are installed by default on many Linuxes such as Ubuntu.

BSD vs GNU can cause confusion in other situations, so I often open the manual page of the corresponding tool to quickly check whether I'm using the BSD or GNU version. If you have the GNU coreutils installed (via homebrew) then you may need to prepend `g` (e.g, `gpaste` to get the GNU version.

So this is not a typo, but since your suggestion works for both GNU and BSD versions I think it's a good idea to change the text. Thanks. Are you in the mood to submit a PR for this or shall I make the change?

**Comment by lissahyacinth** [comment]
@jeroenjanssens - Opened a PR, it's referenced in this issue. 

Thanks for the explanation! The BSD/GNU does add some complexity - I do wonder how many of them have mutual solutions, and how many need highlighting in a way, like sed's extra ~ operator in the GNU version for finding odd lines.

**Comment by jeroenjanssens** [comment]
For the second edition, I'll do my best to make all the examples compatible with both GNU and BSD. Thanks again for catching this.
